"""Generative layer: draft the credit memo and the adverse-action notice.

The LLM only *writes up* facts the rule engine and model already produced; it
does not make the credit decision (fluency is not evidence of truth, Class 2).
Uses Google Gemini when GEMINI_API_KEY is set, otherwise a deterministic
template so the demo always runs.
"""

from __future__ import annotations

import json
import os

from .decision import Recommendation

HARD_STOP_FACTOR = {"H01": "dscr", "H02": "bankruptcy_7y", "H03": "credit_score"}

PROMPT = """You are drafting an internal credit memo for a community-bank small-business loan.
Use ONLY the facts in the JSON below. Do not invent numbers, names, or policies.
If something is not in the JSON, say it is not provided.
Sections: 1) Request summary 2) Key ratios 3) Risk assessment (cite rule IDs)
4) Recommendation and conditions 5) Items for the underwriter to verify.
Keep it under 350 words, plain professional English.
If the recommendation is DECLINE, end with a draft adverse-action statement listing
the principal reasons in plain language (ECOA / Regulation B style), max 4 reasons.

JSON:
{payload}
"""


def _payload(app: dict, rec: Recommendation) -> dict:
    keep = ["industry", "loan_amount", "term_months", "years_in_business", "annual_revenue", "ebitda",
            "credit_score", "dscr", "collateral_coverage", "loan_to_revenue", "hazard_zone",
            "hazard_insurance"]
    return {
        "application": {k: rec.facts.get(k) for k in keep},
        "recommendation": rec.decision, "risk_grade": rec.grade,
        "probability_of_default": None if rec.pd is None else round(rec.pd, 3),
        "rules_fired": [{"id": t["rule"], "action": t["action"], "message": t["message"]} for t in rec.trace],
        "model_reason_codes": [r["reason"] for r in rec.reasons],
    }


def template_memo(app: dict, rec: Recommendation) -> str:
    f = rec.facts
    money = lambda v: "n/a" if v is None else f"${v:,.0f}"  # noqa: E731
    lines = [
        "CREDIT MEMO (draft - generated by UnderwriteIQ, requires underwriter review)",
        "",
        f"Request: {money(f.get('loan_amount'))} over {f.get('term_months')} months for a "
        f"{f.get('industry')} business, {f.get('years_in_business')} years in operation.",
        f"Key ratios: DSCR {f.get('dscr', 'n/a')}x | collateral coverage {f.get('collateral_coverage', 'n/a')}x | "
        f"loan/revenue {f.get('loan_to_revenue', 'n/a')} | owner credit score {f.get('credit_score', 'n/a')}.",
        "",
        f"Recommendation: {rec.decision}" + (f" (risk grade {rec.grade}, PD {rec.pd:.1%})" if rec.pd is not None else ""),
        rec.headline,
    ]
    for title, items in [("Information required", rec.asks), ("Policy hard stops", rec.hard_stops),
                         ("Conditions precedent", rec.conditions), ("Items to review", rec.flags),
                         ("Escalation", rec.referrals), ("Compensating factors", rec.mitigants)]:
        if items:
            lines += ["", title + ":"] + [f"  - {m}" for m in items]
    if rec.reasons:
        lines += ["", "Main model risk drivers:"] + [f"  - {r['reason']}" for r in rec.reasons]
    if rec.decision == "DECLINE":
        # a model reason that restates a fired hard stop is not a separate reason
        covered = {HARD_STOP_FACTOR[t["rule"]] for t in rec.trace if t["rule"] in HARD_STOP_FACTOR}
        principal = (rec.hard_stops + [r["reason"] for r in rec.reasons if r["factor"] not in covered])[:4]
        lines += ["", "Draft adverse-action reasons (for compliance review):"] + [f"  {i}. {m}" for i, m in
                                                                                  enumerate(principal, 1)]
    return "\n".join(lines)


def draft_memo(app: dict, rec: Recommendation) -> tuple[str, str]:
    """Return (memo_text, engine_used)."""
    key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if key:
        try:
            from google import genai  # pip install google-genai
            client = genai.Client(api_key=key)
            resp = client.models.generate_content(
                model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
                contents=PROMPT.format(payload=json.dumps(_payload(app, rec), indent=2, default=str)))
            if resp.text:
                return resp.text, "gemini"
        except Exception as exc:  # fall back rather than break the demo
            return template_memo(app, rec) + f"\n\n[LLM unavailable, template used: {exc}]", "template"
    return template_memo(app, rec), "template"
